import React from 'react';
import { StorySegment as StorySegmentType } from '../types';

interface StorySegmentProps {
  segment: StorySegmentType;
}

export const StorySegment: React.FC<StorySegmentProps> = ({ segment }) => {
  const isUser = segment.role === 'user';

  if (isUser) {
    return (
      <div className="flex justify-end mb-6 animate-fade-in">
        <div className="max-w-[80%] bg-purple-900/40 border border-purple-700/50 rounded-2xl rounded-tr-none p-4 text-purple-100">
          <p className="text-base">{segment.text}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col mb-8 animate-fade-in w-full">
      {/* Narrative Text */}
      <div className="prose prose-invert max-w-none mb-4">
        <div className="bg-gray-800/40 p-5 rounded-lg border-l-4 border-purple-500">
          <p className="text-gray-100 text-lg leading-relaxed font-serif whitespace-pre-wrap">
            {segment.text}
          </p>
        </div>
      </div>

      {/* Generated Image */}
      {(segment.imageUrl || segment.isLoadingImage) && (
        <div className="relative w-full aspect-video rounded-lg overflow-hidden border border-gray-700 shadow-lg bg-black mb-4 group">
          {segment.isLoadingImage ? (
            <div className="absolute inset-0 flex flex-col items-center justify-center bg-gray-900 text-gray-400">
              <svg className="animate-spin h-8 w-8 text-purple-500 mb-3" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              <span className="text-sm font-medium animate-pulse">Painting scene...</span>
            </div>
          ) : (
            <img 
              src={segment.imageUrl} 
              alt="Scene visualization" 
              className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
            />
          )}
          <div className="absolute bottom-0 left-0 right-0 p-2 bg-gradient-to-t from-black/80 to-transparent opacity-0 group-hover:opacity-100 transition-opacity">
            <span className="text-xs text-gray-300 ml-2">Generated by gemini-3-pro-image-preview</span>
          </div>
        </div>
      )}
    </div>
  );
};
